package com.scc.campanha.database;

public abstract class ConsultasSQL {

    //INSERTS
    public static final String INSERIR_PERFIL_REDE_SOCIAL = "INSERT INTO PERFIL_REDE_SOCIAL (PRS_NOME_USUARIO, PRS_REDE_SOCIAL) " +
            "VALUES (:NOME_REDE, :NOME_USUARIO)";

    public static final String INSERIR_REDE_SOCIAL_DIVULGADOR = "INSERT INTO REDE_SOCIAL_DIVULGADOR(RSD_DIVULGADOR_CPF," +
            "RSD_REDE_SOCIAL_NOME_USUARIO, RSD_REDE_SOCIAL_REDE_SOCIAL, RSD_HORAS_VOLUNTARIADO)" +
            " VALUES (:CPF_DIVULGACAO, :NOME_USUARIO, :NOME_REDE, :HORAS_VOLUNTARIADO)";

    public static final String INSERIR_PUBLICACAO = "INSERT INTO PUBLICACAO ( P_REDE_SOCIAL_NOME_USUARIO, P_REDE_SOCIAL_REDE_SOCIAL, " +
            "P_CONTEUDO_DIVULGADO_TITULO, P_CONTEUDO_DIVULGADO_ANO, P_DATA_HORA, P_ALCANCE, P_TOTAL_CLIQUES, P_IMPRESSOES)\n" +
            " VALUES (:REDE_USUARIO, :REDE_REDE, :CONTEUDO_DIVULGADO_TITULO, " +
            ":CONTEUDO_DIVULGADO_ANO, :DATA_HORA, :ALCANCE, :TOTAL_CLIQUES, :IMPRESSOES)";
}
