package com.scc.campanha.database;


/*
*      Aqui estão todas as consultas feitas, isto é, toda interação com o banco, em SQL.
* */
public abstract class ConsultasSQL {

    //INSERTS
    public static final String INSERIR_VOLUNTARIO = "INSERT INTO VOLUNTARIO " +
            "(V_CPF, V_NOME, V_EMAIL, V_TIPO_VOLUNTARIO, V_CIDADE_ENDERECO, V_RUA_ENDERECO, V_BAIRRO_ENDERECO, V_NUMERO_ENDERECO, V_CEP_ENDERECO) " +
            "VALUES(:CPF, :NOME, :EMAIL, :TIPO, :CIDADE, :RUA, :BAIRRO, :NUMERO, :CEP)";

    public static final String INSERIR_PERFIL_REDE_SOCIAL = "INSERT INTO PERFIL_REDE_SOCIAL (PRS_NOME_USUARIO, PRS_REDE_SOCIAL) " +
            "VALUES (:NOME_REDE, :NOME_USUARIO)";

    public static final String INSERIR_REDE_SOCIAL_DIVULGADOR = "INSERT INTO REDE_SOCIAL_DIVULGADOR(RSD_DIVULGADOR_CPF," +
            "RSD_REDE_SOCIAL_NOME_USUARIO, RSD_REDE_SOCIAL_REDE_SOCIAL, RSD_HORAS_VOLUNTARIADO)" +
            " VALUES (:CPF_DIVULGACAO, :NOME_USUARIO, :NOME_REDE, :HORAS_VOLUNTARIADO)";

    public static final String INSERIR_PUBLICACAO = "INSERT INTO PUBLICACAO ( P_REDE_SOCIAL_NOME_USUARIO, P_REDE_SOCIAL_REDE_SOCIAL, " +
            "P_CONTEUDO_DIVULGADO_TITULO, P_CONTEUDO_DIVULGADO_ANO, P_DATA_HORA, P_ALCANCE, P_TOTAL_CLIQUES, P_IMPRESSOES)\n" +
            " VALUES (:REDE_USUARIO, :REDE_REDE, :CONTEUDO_DIVULGADO_TITULO, " +
            ":CONTEUDO_DIVULGADO_ANO, :DATA_HORA, :ALCANCE, :TOTAL_CLIQUES, :IMPRESSOES)";

    public static final String BUSCAR_CONTEUDO_MAIS_CLIQUES_POR_PERIODO = "SELECT CD.CD_TITULO, CD.CD_PUBLICO_ALVO, AVG(P_TOTAL_CLIQUES) AS MEDIA_DE_CLIQUES_CONTEUDO " +
            "FROM PUBLICACAO P " +
            "JOIN CONTEUDO_DIVULGADO CD " +
            "ON CD.CD_TITULO = P.P_TITULO_CONTEUDO_DIVULGADO AND CD.CD_ANO_CRIACAO = P.P_ANO_CONTEUDO_DIVULGADO " +
            "WHERE P.P_TOTAL_CLIQUES > ( " +
                "SELECT AVG(P1.P_TOTAL_CLIQUES) FROM PUBLICACAO P1 " +
            ") "+
            "AND EXTRACT(MONTH FROM P.P_DATA_HORA) BETWEEN :MES_INICIO AND :MES_FIM " +
            "GROUP BY CD.CD_TITULO, CD.CD_PUBLICO_ALVO " +
            "ORDER BY MEDIA_DE_CLIQUES_CONTEUDO DESC";
}
