package com.scc.campanha.database;


/*
*      Aqui estão todas as consultas feitas, isto é, toda interação com o banco, em SQL.
* */
public abstract class ConsultasSQL {

    public static final String INSERIR_VOLUNTARIO = "INSERT INTO VOLUNTARIO " +
            "(V_CPF, V_NOME, V_EMAIL, V_TIPO_VOLUNTARIO, V_CIDADE_ENDERECO, V_RUA_ENDERECO, V_BAIRRO_ENDERECO, V_NUMERO_ENDERECO, V_CEP_ENDERECO) " +
            "VALUES(:CPF, :NOME, :EMAIL, :TIPO, :CIDADE, :RUA, :BAIRRO, :NUMERO, :CEP)";

    public static final String BUSCAR_VOLUNTARIO_POR_CPF = "SELECT V_CPF, V_NOME, V_EMAIL, V_TIPO_VOLUNTARIO  " +
            "FROM VOLUNTARIO WHERE V_CPF = :CPF";
    public static final String BUSCAR_TRIAGENS_DOACOES_DE_CENTROS = "SELECT CENTRO_RUA, CENTRO_BAIRRO, CO2.CO_NUMERO AS CENTRO_NRO, " +
            "COALESCE(CO_QTD_TRIADA, 0) AS QTD_TRIAGENS,  " +
            "COALESCE(SUM(D.D_QUANTIDADE_ROUPAS), 0) AS QTD_ARRECADACOES, " +
            "CASE WHEN CO2.CO_IS_ARRECADACAO = 'S' AND CO2.CO_IS_TRIAGEM = 'S' THEN 'AMBOS' " +
            "     WHEN CO2.CO_IS_ARRECADACAO = 'N' AND CO2.CO_IS_TRIAGEM = 'S' THEN 'TRIAGEM' " +
            "     ELSE 'ARRECADACAO' END AS TIPO " +
            "FROM ( " +
                "SELECT CO.CO_RUA as CENTRO_RUA,  " +
                "CO.CO_BAIRRO as CENTRO_BAIRRO,  " +
                "SUM(PT.PT_QUANTIDADE) AS CO_QTD_TRIADA  " +
                "FROM CENTRO_OPERACIONAL CO " +
                "LEFT JOIN PACOTE_TRIADO PT ON PT.PT_ID_CENTRO_TRIAGEM = CO.CO_ID  " +
                "GROUP BY CO.CO_RUA, CO.CO_BAIRRO " +
            ") " +
            "JOIN CENTRO_OPERACIONAL CO2 ON CO2.CO_RUA = CENTRO_RUA AND CO2.CO_BAIRRO = CENTRO_BAIRRO " +
            "LEFT JOIN DOACAO D ON CO2.CO_ID = D.D_ID_CENTRO_ARRECADACAO " +
            "   AND EXTRACT(MONTH FROM D.D_DATA_HORA) BETWEEN :MES_INICIO AND :MES_FIM " +
            "GROUP BY CENTRO_RUA, CENTRO_BAIRRO, CO2.CO_NUMERO, CO_QTD_TRIADA, CO2.CO_IS_ARRECADACAO, CO2.CO_IS_TRIAGEM";

}
